apiVersion: v1
kind: Pod
metadata:
  name: database
  labels:
    app: database
spec:
  containers:
   - name: database
     image: techvakeelm32/my-sql:v1

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: techvakeelm32/spring-with-mysql:v1
        env:
      # Use secret in real life
         - name: "spring.datasource.url"
           value: "jdbc:mysql://172.17.0.6:3306/test"